language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
script:
- "./gradlew build"
#after_success:
#- chmod +x HelloWorld.sh
#- "./HelloWorld.sh"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
branches:
  only:
  - master
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: "T47v0xlFIza7BtOIuG0oq3I3EnNOnMi7O0dA3qBzDTtdqzkmm+uQ2wsRPa1ATdoAmZdcBsl93DyFbQwvXkP6hE7PYGmqeZFzqZzvTlHQvk9J6NbUiLcBn1Lm1fK7+ThLmdbBgIYucE/dSiiYupKLL7EkRM6PVo+Nj2JDUSLOyyyWtDjfE/pg9akp/vIW08oT8b4X/ruZkO0frQ4S8XTJlCRbxuWEWGlfLZ7p4/u+RqbS+Gy7BsacPbFdtyOBSJcztsFjAY+HsLSDvyy822HmvYq2DYAzk7Fl1mSdPlZn1OJa92ycPgf29T0iFlApqPfsyD6ZWbg0TDgI9bXC0ZYxrljCWWJY7c2UDZUKv6sB/sU8BZGh2qQ1K8kEpYABD7pqaVebzOm1fGH5WW2CUiFrNprt5yGpcEF3F75bo0w3BNnnZwH1Bg548HLBm5+IgUjjpuxTQUwdcZHFi0xq8BtT0/H97Ix/TsoAlSfkTHSlei9AERlZI+p/Q8wEZG0SPxzs3eRm9sHOfQT2PrmVwxGBT0RBLmmBfMDlql1AFKUk/5VJ07lGlRdGjY+caiFnMlUWqk96ARM+/iLCe4Bb3EMPmJl4MwLym+x5219Cq1xzHZ24BL9FZmthIfwJAdX7AgTcfASff+YxJtDdm2ywRQXPuPSL/XjnQ3lAk6l1V6tgv7Y="
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    repo: adrianwithah/CICDTesting

