language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools    
    - extra-android-m2repository

script:
  - ./gradlew build
  
after_success:
  - chmod +x HelloWorld.sh
  - ./HelloWorld.sh
  
before_install:
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
branches:
        only:
                - master
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  
deploy:
  provider: releases
  api_key: "bff4d1f11c888fb41268870f6cd36ff47c2e8c5f"
  file: "app/build/outputs/apk/debug/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
