language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
script:
- "./gradlew build"
#after_success:
#- chmod +x HelloWorld.sh
#- "./HelloWorld.sh"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
branches:
  only:
  - master
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: "T9vjAKSMcXoADFANG4fR362yyose5WjBSb8TuMB/anOeryg0eeFKiSlACiim4nRqvvW87b6SRGVCLQk3HjpLKmuOw/9CiyOhYNtloGV0qMuGDSC+T5yP5/U7h1uLWMs/HtZon2Twh/S3KaLvNuIEtZsxvZXVUu8APw+Xx/MxMkvvbwcRrajD+ECL42bhv7urSLP7hWrI4aq+cdPAicmZZeS98NS5QtmzJ7/gotSj8+jlPrDrDSpt+vIiAiC4x7G1RdXeceziXeYr7tnPt9XDAzkHuAt0O8w8e7aDd/bkg3St/zLRM74x0mNEXD7GQ/ZovSz92OhrBej11AhihGoBC1Hi/g2QVmY6TE1Xm1ilrz8Hm2XaDpUBDy6lVDaOMJmS8OcfnFWnou56wK8xyIzfs6YzIHeeGNyHxm7WPx1uti1Nru48RMNhmB+Bl88WgMDP+7y336SeR0lEKK2prfxHzvTLNokiPVKdc6wTAl6FREw4vidCvm7OfuXErjKsyRhAxixqcL1TBJCTXvhcria/UCivUYLA4+5q1x/fuQ9ek7jcIOLpe51c9ZSdiaDdNsY2o7mmCSKyp1/JIItEBVOUiIjX9I2IyLh7LXxaHPyLCmE5kGw0GEzLCJ71u3Ubq8b/Y6I1PQLBz/+qbM9YSxpQhkdmi7/2ntxR2beSGoEbZSc="
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    repo: adrianwithah/CICDTesting

