language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools    
    - extra-android-m2repository

script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;29.0.0"
branches:
        only:
                - master
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
