language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
script:
- "./gradlew build"
#after_success:
#- chmod +x HelloWorld.sh
#- "./HelloWorld.sh"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
branches:
  only:
  - master
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: "QeIC32VEzeaBupnbOAe4uiydvpw4Ai9Uf8rCDv1Y8wn9liQ/8wi0E972TtKtjq2w5ueq+T4h52smh+w6h5vn3y9DPeqVCwpt0I/6l5iItyCb+HjEcCcTjDa/sJFPgR4ZaWddhhUuPoM64+QZFsdtuQB2EkSl3qxLCAyjr/AcQ9Xfmad8CEZIhdIHrHEE8h8A4axXMsmgg0n7fd38TU/BLQEBx/Rtuhr4UmEuqCoPJ6p2bTeOvyVmORds2Y4chE16hjYJR9oGHLvedZO40+zbBTG8i8KUpYEflPFDGKOY3HMv+Kgj7mKgHqYXNfthxZxMMgGitPydMC2ETdvQSg81U2JJjXLRZg/EZOcYn9RqP9HyjhAlYalbK8wyAE4DD938Lq+/iej9YTHmXHKP/YOH79mBbX/E7LpqBUE+zMhSa9hSeuzw/d0teolAQU91+9jPhhnoRpuW4BwdKgivjrOVrqWlvcMfnPvcga6iGmroMEI/2WKsAxfUJfZe+wOW+Qz0hjAIg1PhQ+F6GJ5cNViS37rfBxOQzHuPvX33SLiibQghaQt9UPSneFdlTSIap0L9J+wMzD0bTlxrO7Rr7eqhyg8p5nTGvUfl2mVkxxvscHmlPNMat6g+OSijRYjcssUjhlt+Cn9qeQFfgAATMCyz7KHEtHhcRkMlt+Gna0V2oBY="
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    repo: adrianwithah/CICDTesting

