language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - extra-android-m2repository
script:
- "./gradlew build"
after_success:
- chmod +x HelloWorld.sh
- "./HelloWorld.sh"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
branches:
  only:
  - master
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
deploy:
  provider: releases
  user: adrianwithah
  password:
    secure: VnfK6vC/i6jf7Jlg4YTqr1KVbY4wTfCcCw0+10iZLKKgAs9KcO0vozQoX6dCwc2JtSO4REpITgzONsIwb1+wJwnTA2BML4T6iDFakS7cLVQwxMFybAel5fTYrgzlw1dSi2L5V4jDY51b+6QQ56+X4NfpLdUHKv/tGjHbzIi81J5GoJV+5+KdtlTyjFsPYGaisgfzAM5wwjIZtyE4zJhenqSfgxbWqdR1YJV+uvgnK9vkF9XelMgs/3/onLPy4dLrjJrgIETeTvoh7UFQ/fGpDyVYl05dr3ji/cCgko3g+QX5KXW+VuvtAGdvshpErileIfGXwVOKDcrksP3Ci3wvFNMviX+h8Valm3wzPxXjIexcYhQIGvENlKnXIwfma8XOCQxr10CS92HNTzg9e7wYaXi+/rD7QfS/XQGMoHephEbxVQNP2CDtsMVyKYGUkOCfu6JAotEWjr4ob4zp1Uf+FIDSFxwwzkvTW0rnOjr45IZ8igybzFIZhD2XDR62Z1CniVGgh8PlWFnlR6zdT+W6spR4NhPsSLh1XXzSK8IjhXxmy14qI+NqSmWrHikW5PyAwFqTogUgUf7s76hDKI58Mct/DH1dnjHCTA9ATAvZklxTBFbSTdiUV1KW/KYzevMchGYB+8AR2z238VLztXVl9PDuWpEKynxesKZLZh5UwFs=
  file: app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  on:
    repo: adrianwithah/CICDTesting

